from joblib import PrintTime
import gpflow
from gpflow.likelihoods import ScalarLikelihood
from gpflow import Parameter
from gpflow.utilities import positive
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow_probability import distributions as tfd
from s0_fun_IBM import IBM_1step, full_dataset_generator
from s0_fun_perturbation import list_comparisons, model_perturbation
import ray
import multiprocessing
import sys


class GP_IPM:
    def __init__(self, popu_data, GPmodel_true, NB=None):
        # popu_data is the observed dataset 
        # GPmodel_true is the true model generate the simulated population behind.
        # NB is a boolean to indicate whether Negative Binomial model is used for flowring stalks.
        # size_t and age_t are the individual state at time t (without considering newborns at t+1)
        self.popu_data = popu_data
        self.GPmodel_true = GPmodel_true
        self.NB = NB
        self.size_t = self.size_t_compu
        self.age_t = self.age_t_compu
    
    @property
    def age_t_compu(self):
        return self.popu_data.loc[self.popu_data['age'].notna(), 'age']
    
    @property
    def size_t_compu(self):
        return self.popu_data.loc[self.popu_data['size'].notna(), 'size']



class Perted_IPM(GP_IPM):
    def __init__(self, popu_data, GPmodel_true, NB, target, mcmc_para_sample=None, summary='Full', 
                       nlog_likeli=None, nlog_post=None, opt_percentage=None): 
        # mcmc_para_sample: is the sample of hyperparameters generated by HMC for the model.
        # nlog_post: negative log posterior at training data points.
        # nlog_likeli: negative log likelihood at training data points.
        # rep: the number of repeat during simulations.   
        
        # initializing attributes by give inputs
        super(Perted_IPM, self).__init__(popu_data=popu_data, GPmodel_true=GPmodel_true, NB=NB)
        self.target = target 
        self.mcmc_para_sample = mcmc_para_sample
        self.nlog_likeli = nlog_likeli
        self.nlog_post = nlog_post
        self.opt_percentage = opt_percentage

        # computing attributes through give inputs
        
        if summary != 'Full':
            assert False, '\n We are still working hard to develop this function! Please come back later.'
        else:
            self.col_names = ['1c', '1d', '1e', '1f', '1g', '2c', '2d', '2e', '2f', '2g', 
                              '3c', '3d', '3e', '3f', '3g', 
                              '4a', '4b', '5a', '5b', '6a', '6b', '7a', '7b', '8a', '8b',
                              '9a', '9b', '10a', '10b', '11a', '11b', '12a', '12b', '13a', '13b',
                              '14a', '14b','15a', '15b', 
                              '16b','17b','18b','19b','20b','21b','22b','23b','24b',
                              '25c', '25d', '25e', '25f', '25g', '26c', '26d', '26e', '26f', '26g',
                              '27c', '27d', '27e', '27f', '27g', '28c', '28d', '28e', '28f', '28g',
                              '29c', '29d', '29e', '29f', '29g',
                              'raw_age', 'raw_size', 'raw_flow']

        if self.target == 'm_sur':
            self.X_sur, self.Y_sur = self.XY_sur_compu
        elif self.target == 'm_grw_f':
            self.X_grw_f, self.Y_grw_f = self.XY_grw_f_compu
        elif self.target == 'm_grw_nf':
            self.X_grw_nf, self.Y_grw_nf = self.XY_grw_nf_compu 
        elif self.target == 'm_fec': 
            self.X_fec, self.Y_fec = self.XY_fec_compu
        elif self.target == 'm_flow_poi': 
            self.X_flow, self.Y_flow = self.XY_flow_compu
        elif self.target == 'm_flow_nb': 
            self.X_flow, self.Y_flow = self.XY_flow_compu 
        else:
           assert False, '\n target is not supported. We are still working hard to develop this function! Please come back later.' 
        # some other attribute would be used latter
        
    @property
    def XY_sur_compu(self):
        index_sur = np.logical_not(np.isnan(self.popu_data["surv"]))
        size_sur = self.popu_data["size"][index_sur].to_numpy()
        surv_sur = self.popu_data["surv"][index_sur].to_numpy()
        age_sur = self.popu_data["age"][index_sur].to_numpy()
        X_sur = np.concatenate((size_sur[:, None], age_sur[:, None]), axis=1)
        Y_sur = surv_sur[:, None]

        return (X_sur, Y_sur)

    @property
    def XY_grw_f_compu(self):
        index_grw = np.logical_not(np.isnan(self.popu_data["sizeNext"])) & np.logical_not(np.isnan(self.popu_data["size"]))
        fec_grw = self.popu_data["fec"][index_grw]
        
        size_grw_f = self.popu_data["size"][index_grw][fec_grw == 1].to_numpy()
        sizeNext_grw_f = self.popu_data["sizeNext"][index_grw][fec_grw == 1].to_numpy()
        age_grw_f = self.popu_data["age"][index_grw][fec_grw == 1].to_numpy()
        X_grw_f = np.concatenate((size_grw_f[:, None], age_grw_f[:, None]), axis=1)
        Y_grw_f = sizeNext_grw_f[:, None]

        return (X_grw_f, Y_grw_f)
    

    @property
    def XY_grw_nf_compu(self):
        index_grw = np.logical_not(np.isnan(self.popu_data["sizeNext"])) & np.logical_not(np.isnan(self.popu_data["size"]))
        fec_grw = self.popu_data["fec"][index_grw]
        
        size_grw_nf = self.popu_data["size"][index_grw][fec_grw == 0].to_numpy()
        sizeNext_grw_nf = self.popu_data["sizeNext"][index_grw][fec_grw == 0].to_numpy()
        age_grw_nf = self.popu_data["age"][index_grw][fec_grw == 0].to_numpy()
        X_grw_nf = np.concatenate((size_grw_nf[:, None], age_grw_nf[:, None]), axis=1)
        Y_grw_nf = sizeNext_grw_nf[:, None]

        return (X_grw_nf, Y_grw_nf)


    @property
    def XY_fec_compu(self):
        index_fec = np.logical_not(np.isnan(self.popu_data["fec"]))
        size_fec = self.popu_data["size"][index_fec].to_numpy()
        fec_fec = self.popu_data["fec"][index_fec].to_numpy()
        age_fec = self.popu_data["age"][index_fec].to_numpy()
        X_fec = np.concatenate((size_fec[:, None], age_fec[:, None]), axis=1)
        Y_fec = fec_fec[:, None]

        return (X_fec, Y_fec)

    @property
    def XY_flow_compu(self):
        index_flow = self.popu_data["fec"] == 1
        size_flow = self.popu_data["size"][index_flow].to_numpy()
        flow_flow = self.popu_data["flow"][index_flow].to_numpy()
        age_flow = self.popu_data["age"][index_flow].to_numpy()
        X_flow = np.concatenate((size_flow[:, None], age_flow[:, None]), axis=1)
        Y_flow = flow_flow[:, None] - 1

        return (X_flow, Y_flow)


    @property
    def build_new_m_sur(self):
        if self.target != 'm_sur':
            warnings.warn("Building new m_sur, but the target is not m_sur")

        f64 = gpflow.utilities.to_default_float
        l = gpflow.likelihoods.Bernoulli()
        kernel = gpflow.kernels.RBF(lengthscales=np.array([1,1]))

        m_sur_new = gpflow.models.GPMC(data=(self.X_sur, self.Y_sur), kernel=kernel, likelihood=l)
        m_sur_new.kernel.lengthscales.prior = tfd.InverseGamma(f64(0.001),f64(0.001))
        m_sur_new.kernel.variance.prior = tfd.InverseGamma(f64(0.001),f64(0.001))

        return m_sur_new


    @property
    def build_new_m_grw_f(self):
        if self.target != 'm_grw_f':
            warnings.warn("Building new m_grw_f, but the target is not m_grw_f.")

        f64 = gpflow.utilities.to_default_float
        kernel = gpflow.kernels.RBF(lengthscales=np.array([1,1]))
        m_grw_f_new = gpflow.models.GPR(data=(self.X_grw_f, self.Y_grw_f), kernel=kernel)
        m_grw_f_new.kernel.lengthscales.prior = tfd.InverseGamma(f64(0.001),f64(0.001))
        m_grw_f_new.kernel.variance.prior = tfd.InverseGamma(f64(0.001),f64(0.001))
        m_grw_f_new.likelihood.variance.prior = tfd.InverseGamma(f64(0.001),f64(0.001))

        return m_grw_f_new


    @property
    def build_new_m_grw_nf(self):
        if self.target != 'm_grw_nf':
            warnings.warn("Building new m_grw_nf, but the target is not m_grw_nf.")

        f64 = gpflow.utilities.to_default_float
        kernel = gpflow.kernels.RBF(lengthscales=np.array([1,1]))
        m_grw_nf_new = gpflow.models.GPR(data=(self.X_grw_nf, self.Y_grw_nf), kernel=kernel)
        m_grw_nf_new.kernel.lengthscales.prior = tfd.InverseGamma(f64(0.001),f64(0.001))
        m_grw_nf_new.kernel.variance.prior = tfd.InverseGamma(f64(0.001),f64(0.001))
        m_grw_nf_new.likelihood.variance.prior = tfd.InverseGamma(f64(0.001),f64(0.001))

        return m_grw_nf_new


    @property
    def build_new_m_fec(self):
        if self.target != 'm_fec':
            warnings.warn("Building new m_fec, but the target is not m_fec.")

        f64 = gpflow.utilities.to_default_float
        l = gpflow.likelihoods.Bernoulli()
        kernel = gpflow.kernels.RBF(lengthscales=np.array([1,1]))
        m_fec_new = gpflow.models.GPMC(data=(self.X_fec, self.Y_fec), kernel=kernel, likelihood=l)
        m_fec_new.kernel.lengthscales.prior = tfd.InverseGamma(f64(0.001),f64(0.001))
        m_fec_new.kernel.variance.prior = tfd.InverseGamma(f64(0.001),f64(0.001))

        return m_fec_new

    @property
    def build_new_m_flow_poi(self):
        if self.target != 'm_flow_poi':
            warnings.warn("Building new m_flow_poi, but the target is not m_flow_poi.")

        f64 = gpflow.utilities.to_default_float
        kernel = gpflow.kernels.RBF(lengthscales=np.array([1,1]))
        l = gpflow.likelihoods.Poisson()

        m_flow_new = gpflow.models.GPMC(data=(self.X_flow, self.Y_flow), kernel=kernel, likelihood=l)
        m_flow_new.kernel.lengthscales.prior = tfd.InverseGamma(f64(0.001),f64(0.001))
        m_flow_new.kernel.variance.prior = tfd.InverseGamma(f64(0.001),f64(0.001))

        return m_flow_new
    
    @property
    def build_opti(self):

        m_opti = getattr(self, 'build_new_'+self.target)
        for var, var_samples in zip(m_opti.parameters, self.mcmc_para_sample):
            var.assign(var_samples[self.opt_comp])
        
        return m_opti
        


    def build_models(self, m_new):
        new_models = self.GPmodel_true.copy() 
        new_models[self.target] = m_new

        return new_models



##########################################################################################################################
# 1st, we define a function for calculating summary for all MCMC samples 
#      (observed datasets VS simulated datasets generated by given MCMC samples) 
#      (1 dataset VS M datasets generated by M models)
#      (at training data points only).

    def obsVSsimu_fun(self, i):
        # i: a single index of MCMC sample you want to use to do the simulations.
        np.random.seed(self.list_seed[i])

        # model initialize
        m_new = getattr(self, 'build_new_'+self.target)

        # assigning values to hyperparameters from MCMC samples
        for var, var_samples in zip(m_new.parameters, self.mcmc_para_sample):
            var.assign(var_samples[i])

        # simulation setup
        r_data = pd.DataFrame(data=0.0, index=range(self.rep), columns=self.col_names) 
        current_models = self.build_models(m_new)

        try:
            for j in range(self.rep):    
                simu_data = IBM_1step(zt=self.size_t, age=self.age_t, models=current_models, NB=self.NB)
                current_s = list_comparisons(exp_1step_data=self.popu_data, simu_1step_data=simu_data)
                r_data.loc[j] = current_s
        except Exception as e:
            print(f"\n\n\n\n\n\n\n\n\nErrors detacted at sample {i} \n\n\n\n\n\n\n\n\n")
            sys.exit(e) 

        r_data['nlpo'] = np.array(- m_new.log_posterior_density())
        r_data['nll'] = np.array(- m_new.maximum_log_likelihood_objective())
        r_data['i'] = np.array(self.list_seed[i])     

        return r_data  

    def obsVSsimu_fun_parallel(self, rep, random_seed, MCMC_boolean_list='All'):
        # we consider all the MCMC samples by DEFAULT VALUE of MCMC_boolean_list. 
        if MCMC_boolean_list == 'All':
            MCMC_index_list = np.repeat(True, len(self.mcmc_para_sample[0]))
        elif MCMC_boolean_list == 'Opt':
            MCMC_index_list = self.whether_around_opt_comp
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'
        

        # set random seeds
        self.rep = rep
        num_total_samples = len(self.mcmc_para_sample[0])
        num_current_samples = np.sum(MCMC_index_list)
        self.list_seed = self.list_seed_comp(rep=rep, random_seed=random_seed, num_samples=num_current_samples)

        summary_data = pd.DataFrame(data=0.0,  index=range(0, num_current_samples*rep), 
                                    columns=np.append(self.col_names,['nlpo','nll', 'i'], axis=0))
        
        print(f"\n\n\n\n Parallel computing is starting \n with repeat time {self.rep} and random seed {random_seed}.\n\n\n\n")
        i_list = np.arange(0, num_total_samples)[MCMC_index_list]

        n_actor = multiprocessing.cpu_count()-1
        result_s = []
        simulators = [para_Perted_IPM.remote(self) for _ in range(n_actor)]
        for i in np.arange(0, num_current_samples, n_actor):
            if i == (num_current_samples//n_actor * n_actor):
                remainder_p1 = num_current_samples%n_actor
                result_s.append(ray.get([s.obsVSsimu_fun.remote(i_list[k+i]) for k,s in enumerate(simulators[:remainder_p1])]))
            else: 
                result_s.append(ray.get([s.obsVSsimu_fun.remote(i_list[k+i]) for k,s in enumerate(simulators)]))

        K = len(result_s[0])
        for j in range(len(result_s)):
            for k, result in enumerate(result_s[j]):
                result.index = range(K*rep*j+(k*rep), K*rep*j+(k+1)*rep)
                summary_data.loc[(K*rep*j+(k*rep)):(K*rep*j+(k+1)*rep-1)] = result.copy()
                
        del(self.rep); del(self.list_seed)

        return summary_data


    def obsVSsimu_fun_parallel_old(self, rep, random_seed, MCMC_boolean_list='All'):
        # we consider all the MCMC samples by DEFAULT VALUE of MCMC_boolean_list. 
        if MCMC_boolean_list == 'All':
            MCMC_index_list = np.repeat(True, len(self.mcmc_para_sample[0]))
        elif MCMC_boolean_list == 'Opt':
            MCMC_index_list = self.whether_around_opt_comp
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'
        

        # set random seeds
        self.rep = rep
        num_total_samples = len(self.mcmc_para_sample[0])
        num_current_samples = np.sum(MCMC_index_list)
        self.list_seed = self.list_seed_comp(rep=rep, random_seed=random_seed, num_samples=num_current_samples)

        summary_data = pd.DataFrame(data=0.0,  index=range(0, num_current_samples*rep), 
                                    columns=np.append(self.col_names,['nlpo','nll', 'i'], axis=0))
        
        print(f"\n\n\n\n Parallel computing is starting \n with repeat time {self.rep} and random seed {random_seed}.\n\n\n\n")
        i_list = np.arange(0, num_total_samples)[MCMC_index_list]

        with multiprocessing.Pool(multiprocessing.cpu_count()) as pool:
            result_s = pool.map(self.obsVSsimu_fun, i_list)
        
        for k, result in enumerate(result_s):
            result.index = range((k*rep), ((k+1)*rep))
            summary_data.loc[(k*rep):((k+1)*rep-1)] = result.copy()
        
        del(self.rep); del(self.list_seed)

        return summary_data

    def list_seed_comp(self, rep, random_seed, num_samples):
        assert random_seed is not None, '\n random_seed is needed for simulation! '

        list_seed = np.arange(random_seed, random_seed+num_samples)

        return list_seed

##########################################################################################################################
# 2nd, now, we define another simulation function for calculating summary around optimum 
#      (simulated datasets generated by the interested model VS simulated datasets generated by the other given MCMC samples) 
#      (1 model VS N models)
#      (N datasets generated by 1 model VS N datasets generated by N model)
#      (at FULL data points by default).

#  We define the corresponding @property first.
    @property
    def opt_comp(self):
        assert self.nlog_post is not None, '\n nlog_post is needed! '
        return np.where(self.nlog_post == np.min(self.nlog_post))[0][0]

    @property
    def whether_around_opt_comp(self):
        assert self.nlog_post is not None, '\n nlog_post is needed for simulation! '
        assert self.opt_percentage is not None, '\n opt_percentage is needed for finding MCMC samples around the optimum!'

        return self.nlog_post <= np.percentile(self.nlog_post, self.opt_percentage)


    def simuVSsimu_fun(self, i):
        # i: a single index of MCMC sample you want to use to do the simulations.
        
        # model initialize
        m_new = getattr(self, 'build_new_'+self.target)

        # assigning values to hyperparameters from MCMC samples
        for var, var_samples in zip(m_new.parameters, self.mcmc_para_sample):
            var.assign(var_samples[i])
        models_2 = self.build_models(m_new)
        
        np.random.seed(self.list_seed[i])
        r_data = model_perturbation(models1=self.models_interested, models2=models_2,
                                    popu_dataset=self.full_data, rep_time=self.rep, 
                                    sample_size=None, NB=self.NB, col_names=self.col_names)
        
        r_data['i'] = np.array(i)

        return r_data


    def simuVSsimu_fun_parallel(self, rep, random_seed, interested_models='Opt', MCMC_boolean_list='Opt',
                                        evaluate_at_training=False, opt_percentage=0.02,
                                        lower=-0.5, upper=4.5, m_size=100, max_age=14):

        # interested_models='Opt' means that, we are going to compare the simulated datasets generated by 
        #                                     the model at optimumn VS simulated datasets generated by 
        #                                     the other models based on MCMC samples)                               
        # evaluate_at_training is an indicator to state whether compare models at training data points.
        # lower=-0.5, upper=4.5, m_size=100, max_age=14 are used for generating full datsets.

        # we consider all the MCMC samples by DEFAULT VALUE of MCMC_boolean_list. 
        self.opt_percentage = opt_percentage

        if MCMC_boolean_list == 'All':
            MCMC_index_list = np.repeat(True, len(self.mcmc_para_sample[0]))
        elif MCMC_boolean_list == 'Opt':
            MCMC_index_list = self.whether_around_opt_comp
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'

        # set random seeds
        self.rep = rep
        num_total_samples = len(self.mcmc_para_sample[0])
        num_current_samples = np.sum(MCMC_index_list)
        self.list_seed = self.list_seed_comp(rep=rep, random_seed=random_seed, num_samples=num_total_samples)
        
        # set up: data sets
        if evaluate_at_training == False:
            self.full_data = full_dataset_generator(lower=lower,upper=upper, m_size=m_size, max_age=max_age)
        elif evaluate_at_training == True:
            self.full_data = pd.DataFrame({'size': self.size_t, 'age': self.age_t})            
        else:
            assert False, '\n Shall we compare models at training data points only? evaluate_at_training should be a boolean.'

        summary_data = pd.DataFrame(data=0.0,  index=range(0, num_current_samples*rep), 
                                    columns=np.append(self.col_names,['i']))

        # set up: find the interested model.
        if interested_models == 'True':
            self.models_interested = self.GPmodel_true.copy()
        elif interested_models == 'Opt':

            m_new_opti = getattr(self, 'build_new_'+self.target)

            for var, var_samples in zip(m_new_opti.parameters, self.mcmc_para_sample):
                var.assign(var_samples[self.opt_comp])
            self.models_interested = self.build_models(m_new_opti)
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'

        print(f"\n\n\n\n Parallel computing is starting \n with repeat time {self.rep} and random seed {random_seed}.\n\n\n\n")
        
        i_list = np.arange(0, num_total_samples)[MCMC_index_list]

        n_actor = multiprocessing.cpu_count()-1
        result_s = []
        simulators = [para_Perted_IPM.remote(self) for _ in range(n_actor)]
        for i in np.arange(0, num_current_samples, n_actor):
            if i == (num_current_samples//n_actor * n_actor):
                remainder_p1 = num_current_samples%n_actor
                result_s.append(ray.get([s.simuVSsimu_fun.remote(i_list[k+i]) for k,s in enumerate(simulators[:remainder_p1])]))
            else: 
                result_s.append(ray.get([s.simuVSsimu_fun.remote(i_list[k+i]) for k,s in enumerate(simulators)]))

        K = len(result_s[0])
        for j in range(len(result_s)):
            for k, result in enumerate(result_s[j]):
                result.index = range(K*rep*j+(k*rep), K*rep*j+(k+1)*rep)
                summary_data.loc[(K*rep*j+(k*rep)):(K*rep*j+(k+1)*rep-1)] = result.copy()
                
        del(self.models_interested); del(self.rep); del(self.list_seed); del(self.full_data)
        
        return summary_data


# Calculating the se in IPM
        









##########################################################################################################################
# 3rd, now, we define a simulation function to compare populations generated by the same model.
#      (a simulated dataset generated by a model VS another simulated datasets generated the same model) 
#      (1 model VS 1 model)
#      (N VS N datasets generated by 1 model)
#      (at training data points by default).

    def simuVSsimu_singleModel_fun(self, i):
        # i: a single index of MCMC sample you want to use to do the simulations.
        np.random.seed(self.list_seed[i])

        # generating dataset1
        simu_1step_data1 = IBM_1step(zt=self.full_data["size"], age=self.full_data["age"],
                                     models=self.models_interested, NB=self.NB)
        
        # generating dataset2
        simu_1step_data2 = IBM_1step(zt=self.full_data["size"], age=self.full_data["age"],
                                     models=self.models_interested, NB=self.NB)
        # a list of summary stats at current time
        current_s = list_comparisons(exp_1step_data=simu_1step_data1, simu_1step_data=simu_1step_data2)
                                    
        return current_s


    def simuVSsimu_singleModel_fun_parallel(self, rep, random_seed, interested_models='Opt', 
                                                  evaluate_at_training=False, 
                                                  lower=-0.5, upper=4.5, m_size=100, max_age=14):

        # interested_models='Opt' means that, we are going to compare the simulated datasets generated by 
        #                                     the model at optimumn)                               
        # evaluate_at_training is an indicator to state whether compare models at training data points.
        # lower=-0.5, upper=4.5, m_size=100, max_age=14 are used for generating full datsets.

        # set random seeds
        self.rep = rep
        self.list_seed = self.list_seed_comp(rep=rep, random_seed=random_seed, num_samples=rep)

        # set up: data sets
        if evaluate_at_training == False:
            self.full_data = full_dataset_generator(lower=lower,upper=upper, m_size=m_size, max_age=max_age)
        elif evaluate_at_training == True:
            self.full_data = pd.DataFrame({'size': self.size_t, 'age': self.age_t})            
        else:
            assert False, '\n Shall we compare models at training data points only? evaluate_at_training should be a boolean.'
        
        summary_data = pd.DataFrame(data=0.0,  index=range(0, rep), columns=self.col_names)

        # set up: find the interested model.
        if interested_models == 'True':
            self.models_interested = self.GPmodel_true.copy()
        elif interested_models == 'Opt':

            m_new_opti = getattr(self, 'build_new_'+self.target)

            for var, var_samples in zip(m_new_opti.parameters, self.mcmc_para_sample):
                var.assign(var_samples[self.opt_comp])
            self.models_interested = self.build_models(m_new_opti)
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'
        

        print(f"\n\n\n\n Parallel computing is starting \n with repeat time {self.rep} and random seed {random_seed}.\n\n\n\n")
        
        i_list = np.arange(0, rep)

        n_actor = multiprocessing.cpu_count()-1
        result_s = []
        simulators = [para_Perted_IPM.remote(self) for _ in range(n_actor)]
        for i in np.arange(0, rep, n_actor):
            if i == (rep//n_actor * n_actor):
                remainder_p1 = rep%n_actor
                result_s.append(ray.get([s.simuVSsimu_singleModel_fun.remote(i_list[k+i]) for k,s in enumerate(simulators[:remainder_p1])]))
            else: 
                result_s.append(ray.get([s.simuVSsimu_singleModel_fun.remote(i_list[k+i]) for k,s in enumerate(simulators)]))

        K = len(result_s[0])
        for j in range(len(result_s)):
            for k, result in enumerate(result_s[j]):
                summary_data.loc[K*j+(k)] = result.copy()

        del(self.models_interested); del(self.rep); del(self.list_seed); del(self.full_data)
        
        return summary_data


##########################################################################################################################
# 4th, similar as the 3rd, but now compared with observed dataset.
#      (Observed dataset. VS N datasets generated by 1 model)

    def obsVSsimu_singleModel_fun(self, i):
        # i: a single index of MCMC sample you want to use to do the simulations.
        np.random.seed(self.list_seed[i])

        # generating dataset1
        simu_1step_data = IBM_1step(zt=self.size_t, age=self.age_t, models=self.models_interested, NB=self.NB)

        if self.comparison == 'Full':
            # a list of summary stats at current time
            current_s = list_comparisons(exp_1step_data=self.popu_data, simu_1step_data=simu_1step_data)
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'


                                        
        return current_s


    def obsVSsimu_singleModel_fun_parallel(self, rep, random_seed, interested_models='True',
                                           comparison='Full'):

        # interested_models='Opt' means that, we are going to compare the simulated datasets generated by 
        #                                     the model at optimumn VS observed datset)                               

        # set random seeds
        self.rep = rep
        self.comparison = comparison
        self.list_seed = self.list_seed_comp(rep=rep, random_seed=random_seed, num_samples=rep)

        if self.comparison == 'Full':
            summary_data = pd.DataFrame(data=0.0,  index=range(0, rep), columns=self.col_names)
        elif self.comparison == 'interested':
            summary_data = pd.DataFrame(data=0.0,  index=range(0, rep), columns=['7b', '15a', '19b', '25g', '27e', '6b', '10a'])
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'


        if interested_models == 'True':
            self.models_interested = self.GPmodel_true.copy()
        elif interested_models == 'Opt':
            m_new_opti = getattr(self, 'build_new_'+self.target)
            for var, var_samples in zip(m_new_opti.parameters, self.mcmc_para_sample):
                var.assign(var_samples[self.opt_comp])
            self.models_interested = self.build_models(m_new_opti)
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'

        print(f"\n\n\n\n Parallel computing is starting \n with repeat time {self.rep} and random seed {random_seed}.")
        
        i_list = np.arange(0, rep)
        n_actor = multiprocessing.cpu_count()-1
        result_s = []
        simulators = [para_Perted_IPM.remote(self) for _ in range(n_actor)]
        for i in np.arange(0, rep, n_actor):
            if i == (rep//n_actor * n_actor):
                remainder_p1 = rep%n_actor
                result_s.append(ray.get([s.obsVSsimu_singleModel_fun.remote(i_list[k+i]) for k,s in enumerate(simulators[:remainder_p1])]))
            else: 
                result_s.append(ray.get([s.obsVSsimu_singleModel_fun.remote(i_list[k+i]) for k,s in enumerate(simulators)]))

        K = len(result_s[0])
        for j in range(len(result_s)):
            for k, result in enumerate(result_s[j]):
                summary_data.loc[K*j+(k)] = result.copy()
        
        del(self.models_interested); del(self.rep); del(self.list_seed); del(self.comparison)
        
        return summary_data





@ray.remote
class para_Perted_IPM():
    def __init__(self, m):
        # m is an object belonging to Perted_IPM
        self.m = m
    
    def obsVSsimu_fun(self, i):
        return self.m.obsVSsimu_fun(i)
    
    def simuVSsimu_fun(self, i):
        return self.m.simuVSsimu_fun(i)
    
    def simuVSsimu_singleModel_fun(self, i):
        return self.m.simuVSsimu_singleModel_fun(i)

    def obsVSsimu_singleModel_fun(self, i):
        return self.m.obsVSsimu_singleModel_fun(i)
    
    def simuVSsimu_fun_ipm(self, i):
        return self.m.simuVSsimu_fun_ipm(i)

