import ray
import multiprocessing
from joblib import PrintTime
import gpflow
from gpflow.likelihoods import ScalarLikelihood
from gpflow import Parameter
from gpflow.utilities import positive
import warnings
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow_probability import distributions as tfd
from s0_fun_base import XY_fec_compu, XY_sur_compu, XY_flow_compu, XY_grw_compu, XY_grw_f_compu, XY_grw_nf_compu
from s0_fun_ss import list_comparisons
from s0_fun_IBMs import IBM_1step_gp, IBM_1step_gp_same
from s0_fun_IPMs import kernel_setting
f64 = gpflow.utilities.to_default_float



class GP_IPM:
    def __init__(self, popu_data, GPmodel_true, grw_setting, truedata_style):
        # popu_data is the observed dataset 
        # GPmodel_true is the true model generate the simulated population behind. (Here, is not exactly 
        #               the true model but the models for the calculated mle from the simulated dataset).
        self.popu_data = popu_data
        self.GPmodel_true = GPmodel_true
        self.grw_setting = grw_setting
        self.truedata_style = truedata_style
        self.size_t = self.size_t_compu
        self.age_t = self.age_t_compu
    
    @property
    def age_t_compu(self):
        return self.popu_data.loc[self.popu_data['age'].notna(), 'age']
    @property
    def size_t_compu(self):
        return self.popu_data.loc[self.popu_data['size'].notna(), 'size']



class Perted_IPM(GP_IPM):
    def __init__(self, popu_data, GPmodel_true, grw_setting, target, truedata_style,
                       mcmc_para_sample=None, summary='Full', 
                       nlog_likeli=None, nlog_post=None, opt_percentage=None): 
        # mcmc_para_sample: is the sample of hyperparameters generated by HMC for the model.
        # nlog_post: negative log posterior at training data points.
        # nlog_likeli: negative log likelihood at training data points.
        
        # initializing attributes by give inputs
        super(Perted_IPM, self).__init__(popu_data=popu_data, GPmodel_true=GPmodel_true, grw_setting=grw_setting, truedata_style=truedata_style)
        self.target = target 
        self.mcmc_para_sample = mcmc_para_sample
        self.nlog_likeli = nlog_likeli
        self.nlog_post = nlog_post
        self.opt_percentage = opt_percentage

        # computing attributes through give inputs
        
        if summary != 'Full':
            assert False, '\n We are still working hard to develop this function! Please come back later.'
        else:
            self.col_names = ['1c', '1d', '1e', '1f', '1g', 
                              '4a', '4b', 
                              '7a', '7b', 
                              '10a', '10b', 
                              '13a', '13b',
                              '16b', 
                              '19b',
                              '22b',
                              '25c', '25d', '25e', '25f', '25g', 
                              '27c', '27d', '27e', '27f', '27g', 
                              '29c', '29d', '29e', '29f', '29g',
                              'raw_size', 'raw_flow']

        if self.target == 'm_sur':
            (self.X_sur, self.Y_sur) = self.XY_sur_compu
        elif self.target == 'm_grw_f':
            if self.grw_setting == 'sep' :
                (self.X_grw_f, self.Y_grw_f) = self.XY_grw_f_compu
            else:
                assert False, '\n grw_setting should be sep' 
        elif self.target == 'm_grw_nf':
            if self.grw_setting == 'sep' :
                (self.X_grw_nf, self.Y_grw_nf) = self.XY_grw_nf_compu
            else:
                assert False, '\n grw_setting should be sep'
        elif self.target == 'm_grw':
            if self.grw_setting == 'nonsep' :
                (self.X_grw, self.Y_grw) = self.XY_grw_compu 
            else:
                assert False, '\n grw_setting should be nonsep'
        elif self.target == 'm_fec': 
            (self.X_fec, self.Y_fec) = self.XY_fec_compu
        elif self.target == 'm_flow_poi': 
            (self.X_flow, self.Y_flow) = self.XY_flow_compu
        else:
           assert False, '\n target is not supported. We are still working hard to develop this function! Please come back later.' 
        
    @property
    def XY_sur_compu(self):
        return XY_sur_compu(self.popu_data)

    @property
    def XY_grw_f_compu(self):
        return XY_grw_f_compu(self.popu_data)
    
    @property
    def XY_grw_nf_compu(self):
       return XY_grw_nf_compu(self.popu_data) 
    
    @property
    def XY_grw_compu(self):
       return XY_grw_compu(self.popu_data) 

    @property
    def XY_fec_compu(self):
       return XY_fec_compu(self.popu_data) 

    @property
    def XY_flow_compu(self):
        return XY_flow_compu(self.popu_data)


    @property
    def build_new_m_sur(self):
        if self.target != 'm_sur':
            warnings.warn("Building new m_sur, but the target is not m_sur")

        l = gpflow.likelihoods.Bernoulli()
        kernel = gpflow.kernels.RBF()

        m_sur_new = gpflow.models.GPMC(data=(self.X_sur, self.Y_sur), kernel=kernel, likelihood=l)

        if self.truedata_style == 'glm':
            m_sur_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(50.))
            m_sur_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(50.))
        elif self.truedata_style == 'gp':
            m_sur_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(50.))
            m_sur_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(50.))
        else:
           assert False, '\n truedata_style should be glm or gp' 
 

        return m_sur_new


    @property
    def build_new_m_grw_f(self):
        if self.target != 'm_grw_f':
            warnings.warn("Building new m_grw_f, but the target is not m_grw_f.")

        m_grw_f_new = gpflow.models.GPR(data=(self.X_grw_f, self.Y_grw_f), kernel=gpflow.kernels.RBF())
        if self.truedata_style == 'glm':
            m_grw_f_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_f_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_f_new.likelihood.variance.prior = tfd.HalfNormal(scale=f64(100.))
        elif self.truedata_style == 'gp':
            m_grw_f_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_f_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_f_new.likelihood.variance.prior = tfd.HalfNormal(scale=f64(100.))
        else:
           assert False, '\n truedata_style should be glm or gp' 

        return m_grw_f_new


    @property
    def build_new_m_grw_nf(self):
        if self.target != 'm_grw_nf':
            warnings.warn("Building new m_grw_nf, but the target is not m_grw_nf.")

        m_grw_nf_new = gpflow.models.GPR(data=(self.X_grw_nf, self.Y_grw_nf), kernel=gpflow.kernels.RBF())
        if self.truedata_style == 'glm':
            m_grw_nf_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_nf_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_nf_new.likelihood.variance.prior = tfd.HalfNormal(scale=f64(100.))
        elif self.truedata_style == 'gp':
            m_grw_nf_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_nf_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_nf_new.likelihood.variance.prior = tfd.HalfNormal(scale=f64(100.))
        else:
           assert False, '\n truedata_style should be glm or gp' 
        return m_grw_nf_new


    @property
    def build_new_m_grw(self):
        if self.target != 'm_grw':
            warnings.warn("Building new m_grw, but the target is not m_grw.")

        m_grw_new = gpflow.models.GPR(data=(self.X_grw, self.Y_grw), kernel=gpflow.kernels.RBF())
        if self.truedata_style == 'glm':
            m_grw_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_new.likelihood.variance.prior = tfd.HalfNormal(scale=f64(100.))
        elif self.truedata_style == 'gp':
            m_grw_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))
            m_grw_new.likelihood.variance.prior = tfd.HalfNormal(scale=f64(100.))
        else:
           assert False, '\n truedata_style should be glm or gp' 
        return m_grw_new
    

    @property
    def build_new_m_fec(self):
        if self.target != 'm_fec':
            warnings.warn("Building new m_fec, but the target is not m_fec.")

        m_fec_new = gpflow.models.GPMC(data=(self.X_fec, self.Y_fec), 
                                       kernel=gpflow.kernels.RBF(), likelihood=gpflow.likelihoods.Bernoulli())

        if self.truedata_style == 'glm':
            m_fec_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))
            m_fec_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
        elif self.truedata_style == 'gp':
            m_fec_new.kernel.variance.prior = tfd.InverseGamma(f64(0.001),f64(0.001))
            m_fec_new.kernel.lengthscales.prior = tfd.Normal(loc=f64(0.), scale=f64(100.))
        else:
           assert False, '\n truedata_style should be glm or gp' 

        return m_fec_new

    @property
    def build_new_m_flow_poi(self):
        if self.target != 'm_flow_poi':
            warnings.warn("Building new m_flow_poi, but the target is not m_flow_poi.")

        m_flow_new = gpflow.models.GPMC(data=(self.X_flow, self.Y_flow), 
                                        kernel=gpflow.kernels.RBF(), likelihood=gpflow.likelihoods.Poisson())
        
        # we dont have to grouping here, but just for coding consistent
        if self.truedata_style == 'glm':
            m_flow_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
            m_flow_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))

        elif self.truedata_style == 'gp':
            m_flow_new.kernel.lengthscales.prior = tfd.HalfNormal(scale=f64(100.))
            m_flow_new.kernel.variance.prior = tfd.HalfNormal(scale=f64(100.))
        else:
           assert False, '\n truedata_style should be glm or gp' 

        return m_flow_new


    @property
    def build_opti(self):

        m_opti = getattr(self, 'build_new_'+self.target)
        for var, var_samples in zip(m_opti.parameters, self.mcmc_para_sample):
            var.assign(var_samples[self.opt_comp])
        
        return m_opti
        


    def build_models(self, m_new):
        new_models = self.GPmodel_true.copy() 
        new_models[self.target] = m_new

        return new_models
    
    def list_seed_comp(self, rep, random_seed, num_samples):
        assert random_seed is not None, '\n random_seed is needed for simulation! '

        list_seed = np.arange(random_seed, random_seed+num_samples)

        return list_seed

##########################################################################################################################
#       we define another simulation function for calculating summary around optimum 
#      (simulated datasets generated by the interested model VS simulated datasets generated by the other given MCMC samples) 
#      (1 model VS N models)
#      (N datasets generated by 1 model VS N datasets generated by N model)
#      (at FULL data points by default).

#  We define the corresponding @property first.
    @property
    def opt_comp(self):
        assert self.nlog_post is not None, '\n nlog_post is needed! '
        return np.where(self.nlog_post == np.min(self.nlog_post))[0][0]

    @property
    def whether_around_opt_comp(self):
        assert self.nlog_post is not None, '\n nlog_post is needed for simulation! '
        assert self.opt_percentage is not None, '\n opt_percentage is needed for finding MCMC samples around the optimum!'

        return self.nlog_post <= np.percentile(self.nlog_post, self.opt_percentage)


    def simuVSsimu_fun(self, i):
        # i: a single index of MCMC sample you want to use to do the simulations.
        
        # model initialize
        m_new = getattr(self, 'build_new_'+self.target)

        # assigning values to hyperparameters from MCMC samples
        for var, var_samples in zip(m_new.parameters, self.mcmc_para_sample):
            var.assign(var_samples[i])
        models_2 = self.build_models(m_new)
        
        np.random.seed(self.list_seed[i])
        summary_data = pd.DataFrame(data=0.0,  index=range(self.rep), columns=self.col_names)
        
        for j in range(self.rep):

            current_dataset = self.full_data.copy()

            if self.grw_setting == 'sep':
                # generating dataset with models1
                simu_1step_data1 = IBM_1step_gp(zt=current_dataset["size"], age=current_dataset["age"],
                                                models=self.models_interested)
                
                # generating datasetwith models2
                simu_1step_data2 = IBM_1step_gp(zt=current_dataset["size"], age=current_dataset["age"],
                                                models=models_2)
            else:
                # generating dataset with models1
                simu_1step_data1 = IBM_1step_gp_same(zt=current_dataset["size"], age=current_dataset["age"],
                                                models=self.models_interested)
                
                # generating datasetwith models2
                simu_1step_data2 = IBM_1step_gp_same(zt=current_dataset["size"], age=current_dataset["age"],
                                                models=models_2)

                
            # a list of summary stats at current time
            current_s = list_comparisons(exp_1step_data=simu_1step_data1, simu_1step_data=simu_1step_data2)
            summary_data.iloc[j,:] = current_s        

        summary_data['i'] = np.array(i)

        return summary_data


    def simuVSsimu_fun_parallel(self, rep, random_seed, interested_models='Opt', MCMC_boolean_list='Opt',
                                        evaluate_at_training=False, opt_percentage=0.02,
                                        lower=0, upper=5, m_size=100):

        # interested_models='Opt' means that, we are going to compare the simulated datasets generated by 
        #                                     the model at optimumn VS simulated datasets generated by 
        #                                     the other models based on MCMC samples)                               
        # evaluate_at_training is an indicator to state whether compare models at training data points.
        # lower=-0.5, upper=4.5, m_size=100, max_age=14 are used for generating full datsets.

        # we consider all the MCMC samples by DEFAULT VALUE of MCMC_boolean_list. 
        self.opt_percentage = opt_percentage

        if MCMC_boolean_list == 'All':
            MCMC_index_list = np.repeat(True, len(self.mcmc_para_sample[0]))
        elif MCMC_boolean_list == 'Opt':
            MCMC_index_list = self.whether_around_opt_comp
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'

        # set random seeds
        self.rep = rep
        num_total_samples = len(self.mcmc_para_sample[0])
        num_current_samples = np.sum(MCMC_index_list)
        self.list_seed = self.list_seed_comp(rep=rep, random_seed=random_seed, num_samples=num_total_samples)
        
        # set up: data sets
        if evaluate_at_training == False:
            a = kernel_setting(m_size=m_size, lower=lower, upper=upper)  
            self.full_data = pd.DataFrame({'size': a[0], 'age': np.repeat(1, len(a[0]))}); del(a)        
        elif evaluate_at_training == True:
            self.full_data = pd.DataFrame({'size': self.size_t, 'age': self.age_t})            
        else:
            assert False, '\n Shall we compare models at training data points only? evaluate_at_training should be a boolean.'

        summary_data = pd.DataFrame(data=0.0,  index=range(0, num_current_samples*rep), 
                                    columns=np.append(self.col_names,['i']))

        # set up: find the interested model.
        if interested_models == 'True':
            self.models_interested = self.GPmodel_true.copy()
        elif interested_models == 'Opt':

            m_new_opti = getattr(self, 'build_new_'+self.target)

            for var, var_samples in zip(m_new_opti.parameters, self.mcmc_para_sample):
                var.assign(var_samples[self.opt_comp])
            self.models_interested = self.build_models(m_new_opti)
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'

        print(f"\n\n\n\n Parallel computing is starting \n with repeat time {self.rep} and random seed {random_seed}.\n\n\n\n")
        
        i_list = np.arange(0, num_total_samples)[MCMC_index_list]

        n_actor = multiprocessing.cpu_count()-2
        result_s = []
        simulators = [para_Perted_IPM.remote(self) for _ in range(n_actor)]
        for i in np.arange(0, num_current_samples, n_actor):
            if i == (num_current_samples//n_actor * n_actor):
                remainder_p1 = num_current_samples%n_actor
                result_s.append(ray.get([s.simuVSsimu_fun.remote(i_list[k+i]) for k,s in enumerate(simulators[:remainder_p1])]))
            else: 
                result_s.append(ray.get([s.simuVSsimu_fun.remote(i_list[k+i]) for k,s in enumerate(simulators)]))

        K = len(result_s[0])
        for j in range(len(result_s)):
            for k, result in enumerate(result_s[j]):
                result.index = range(K*rep*j+(k*rep), K*rep*j+(k+1)*rep)
                summary_data.loc[(K*rep*j+(k*rep)):(K*rep*j+(k+1)*rep-1)] = result.copy()
                
        del(self.models_interested); del(self.rep); del(self.list_seed); del(self.full_data)
        
        return summary_data




##########################################################################################################################
# 2nd, now, we define a simulation function to compare populations generated by the same model.
#      (a simulated dataset generated by a model VS another simulated datasets generated the same model) 
#      (1 model VS 1 model)
#      (N VS N datasets generated by 1 model)
#      (at training data points by default).

    def simuVSsimu_singleModel_fun(self, i):
        # i: a single index of MCMC sample you want to use to do the simulations.
        np.random.seed(self.list_seed[i])

        if self.grw_setting == 'sep':
            # generating dataset with models1
            simu_1step_data1 = IBM_1step_gp(zt=self.full_data["size"], age=self.full_data["age"],
                                            models=self.models_interested)
            
            # generating datasetwith models2
            simu_1step_data2 = IBM_1step_gp(zt=self.full_data["size"], age=self.full_data["age"],
                                            models=self.models_interested)
        else:
            # generating dataset with models1
            simu_1step_data1 = IBM_1step_gp_same(zt=self.full_data["size"], age=self.full_data["age"],
                                                models=self.models_interested)
            
            # generating datasetwith models2
            simu_1step_data2 = IBM_1step_gp_same(zt=self.full_data["size"], age=self.full_data["age"],
                                                models=self.models_interested)

        # a list of summary stats at current time
        current_s = list_comparisons(exp_1step_data=simu_1step_data1, simu_1step_data=simu_1step_data2)
                                    
        return current_s


    def simuVSsimu_singleModel_fun_parallel(self, rep, random_seed, interested_models='Opt', 
                                                  evaluate_at_training=False, 
                                                  lower=0, upper=5, m_size=100):

        # interested_models='Opt' means that, we are going to compare the simulated datasets generated by 
        #                                     the model at optimumn)                               
        # evaluate_at_training is an indicator to state whether compare models at training data points.
        # lower=-0.5, upper=4.5, m_size=100, max_age=14 are used for generating full datsets.

        # set random seeds
        self.rep = rep
        self.list_seed = self.list_seed_comp(rep=rep, random_seed=random_seed, num_samples=rep)

        # set up: data sets
        if evaluate_at_training == False:
            a = kernel_setting(m_size=m_size, lower=lower, upper=upper)  
            self.full_data = pd.DataFrame({'size': a[0], 'age': np.repeat(1, len(a[0]))}); del(a)
        elif evaluate_at_training == True:
            self.full_data = pd.DataFrame({'size': self.size_t, 'age': self.age_t})            
        else:
            assert False, '\n Shall we compare models at training data points only? evaluate_at_training should be a boolean.'
        
        summary_data = pd.DataFrame(data=0.0,  index=range(0, rep), columns=self.col_names)
        # summary_data = pd.DataFrame(data=0.0, index=range(1), columns=self.col_names)

        # set up: find the interested model.
        if interested_models == 'True':
            self.models_interested = self.GPmodel_true.copy()
        elif interested_models == 'Opt':

            m_new_opti = getattr(self, 'build_new_'+self.target)

            for var, var_samples in zip(m_new_opti.parameters, self.mcmc_para_sample):
                var.assign(var_samples[self.opt_comp])
            self.models_interested = self.build_models(m_new_opti)
        else: 
            assert False, '\n We are still working hard to develop this function! Please come back later.'
        

        print(f"\n\n\n\n Parallel computing is starting \n with repeat time {self.rep} and random seed {random_seed}.\n\n\n\n")
        
        i_list = np.arange(0, rep)

        n_actor = multiprocessing.cpu_count()-2
        result_s = []
        simulators = [para_Perted_IPM.remote(self) for _ in range(n_actor)]
        for i in np.arange(0, rep, n_actor):
            if i == (rep//n_actor * n_actor):
                remainder_p1 = rep%n_actor
                result_s.append(ray.get([s.simuVSsimu_singleModel_fun.remote(i_list[k+i]) for k,s in enumerate(simulators[:remainder_p1])]))
            else: 
                result_s.append(ray.get([s.simuVSsimu_singleModel_fun.remote(i_list[k+i]) for k,s in enumerate(simulators)]))

        K = len(result_s[0])
        for j in range(len(result_s)):
            for k, result in enumerate(result_s[j]):
                summary_data.loc[K*j+(k)] = result.copy()

        del(self.models_interested); del(self.rep); del(self.list_seed); del(self.full_data)
        
        return summary_data





@ray.remote
class para_Perted_IPM():
    def __init__(self, m):
        # m is an object belonging to Perted_IPM
        self.m = m
    
    def simuVSsimu_fun(self, i):
        return self.m.simuVSsimu_fun(i)
    
    def simuVSsimu_singleModel_fun(self, i):
        return self.m.simuVSsimu_singleModel_fun(i)
